version: 2.1

executors:
  default:
    docker:
      - image: cimg/go:1.21
      - image: cimg/postgres:16.3-postgis
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_PASSWORD: unicode
          POSTGRES_DB: circle_test
      - image: cimg/redis:7.2.5
    working_directory: ~/repo
    environment:
      GOOROT: /home/ubuntu/.gimme/versions/go1.8.linux.amd64
      NODE_VERSION: 7.7.4

jobs:
  test:
    docker:
      - image: cimg/go:1.21
      - image: cimg/postgres:16.3-postgis
        environment:
            POSTGRES_USER: ubuntu
            POSTGRES_PASSWORD: unicode
            POSTGRES_DB: circle_test
      - image: cimg/redis:7.2.5
    executor: default
    steps:
      - checkout
      - run:
            name: Waiting for Postgres to be ready
            command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Setup Database
          command: |
            echo "Running setup.sql"
            PGPASSWORD=unicode psql -h localhost -U ubuntu -d circle_test -f ./platform/pg/setup.sql
      - run:
          name: Execute Go Tests
          command: ./infrastructure/scripts/execute-go-tests
      # Uncomment the following line if you need to run Elm tests
      # - run:
      #     name: Execute Elm Tests
      #     command: ./infrastructure/scripts/execute-elm-tests

  build_and_deploy:
    docker:
      - image: circleci/python:3.7
    executor: default
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Container
          command: ./build
      - run:
          name: Login to DockerHub
          command: docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
      - run:
          name: Push Docker Image
          command: docker push tapglue/snaas

workflows:
  version: 2
  build:
    jobs:
      - test
      - build_and_deploy:
          requires:
            - test  # Ensure tests pass before building and deploying